# Generated by Django 4.1 on 2023-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_customer',
            name='confirm_change_password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_customer',
            name='new_change_password',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
