# Generated by Django 4.1 on 2023-04-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0002_register_customer_confirm_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_customer',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='register_customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register_customer',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='register_customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='register_customer',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='register_customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='register_customer',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
