# Generated by Django 4.1 on 2022-10-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0003_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='catergory',
        ),
    ]
