# Generated by Django 4.1 on 2022-10-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0004_rename_category_product_catergory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PrevPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
