# Generated by Django 4.1 on 2023-04-18 00:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0004_reviewrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairapp.register_customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairapp.product')),
            ],
        ),
    ]
