# Generated by Django 4.1 on 2023-04-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
