# Generated by Django 4.1 on 2023-04-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0006_order_customer_address_order_customer_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
