# Generated by Django 4.1 on 2023-01-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0007_customer_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Register',
        ),
    ]
