# Generated by Django 4.1 on 2023-04-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='upload/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='upload/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='upload/product/'),
        ),
    ]
