# Generated by Django 4.1 on 2023-01-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0009_customer_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Register',
            new_name='register',
        ),
    ]
