# Generated by Django 4.1 on 2023-01-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0014_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='Newss1',
        ),
        migrations.DeleteModel(
            name='reg',
        ),
    ]
