# Generated by Django 4.1 on 2023-01-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0015_delete_new_delete_newss1_delete_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='registers',
        ),
    ]
