# Generated by Django 4.1 on 2023-01-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0016_reg_customer_delete_registers'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='reg_customer',
        ),
    ]
