# Generated by Django 4.1 on 2023-01-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0018_register_delete_customer_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
