# Generated by Django 4.1 on 2023-01-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0019_reg_customer_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='reg_customer',
        ),
    ]
