# Generated by Django 4.1 on 2023-01-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0020_newmodel_delete_reg_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=60)),
                ('emailaddress', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=60)),
                ('confirmpassword', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='NewModel',
        ),
    ]
