# Generated by Django 4.1 on 2023-01-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairapp', '0021_register_customer_delete_newmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_customer',
            name='confirmpassword',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register_customer',
            name='fullname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register_customer',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register_customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='register_customer',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
